# Generated by Django 5.2.14 on 2026-06-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="description",
        ),
    ]
