# Generated by Django 5.2 on 2026-08-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_systemsettings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ping_target',
            field=models.CharField(default='8.8.8.8', max_length=100),
        ),
    ]
