# Generated by Django 5.2.14 on 2026-08-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alert_alert_key_alert_last_seen_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_key',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
