# Generated by Django 5.2.14 on 2026-08-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_alter_alert_alert_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('internet_down', 'Internet'), ('device_down', 'Device'), ('service_down', 'Service'), ('high_latency', 'High Latency'), ('packet_loss', 'Packet Loss')], max_length=30),
        ),
    ]
