# Generated by Django 5.2.14 on 2026-08-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_alter_alert_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='failure_threshold',
            field=models.PositiveIntegerField(default=3, help_text='Number of consecutive failures required to trigger an alert.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='high_latency_critical_ms',
            field=models.FloatField(default=500.0, help_text='Latency in milliseconds that triggers a critical alert.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='high_latency_warning_ms',
            field=models.FloatField(default=200.0, help_text='Latency in milliseconds that triggers a warning.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='hysteresis_enabled',
            field=models.BooleanField(default=True, help_text='Enable consecutive failure/recovery confirmation.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='packet_loss_critical_percent',
            field=models.FloatField(default=30.0, help_text='Packet loss percentage that triggers a critical alert.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='packet_loss_warning_percent',
            field=models.FloatField(default=10.0, help_text='Packet loss percentage that triggers a warning.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='recovery_threshold',
            field=models.PositiveIntegerField(default=2, help_text='Number of consecutive successful checks required to recover an alert.'),
        ),
    ]
