# Generated by Django 5.2.14 on 2026-08-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_systemsettings_failure_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('consecutive_successes', models.PositiveIntegerField(default=0)),
                ('last_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_severity', models.CharField(blank=True, default='', max_length=10)),
                ('last_value', models.FloatField(blank=True, null=True)),
                ('last_message', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
