# Generated by Django 6.0.6 on 2026-08-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_alertstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='dns_hostname',
            field=models.CharField(default='google.com', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tcp_host',
            field=models.CharField(default='www.google.com', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tcp_port',
            field=models.PositiveIntegerField(default=443),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='web_url',
            field=models.URLField(default='https://www.google.com', max_length=500),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='failure_threshold',
            field=models.PositiveIntegerField(default=1, help_text='Number of consecutive failures required to trigger an alert.'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='recovery_threshold',
            field=models.PositiveIntegerField(default=1, help_text='Number of consecutive successful checks required to recover an alert.'),
        ),
    ]
