# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_systemsettings_dns_hostname_systemsettings_tcp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='snmp_reachable',
            field=models.BooleanField(blank=True, default=None, help_text='None = never checked; True/False = last check result.', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_sys_descr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_uptime_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='snmp_enabled',
            field=models.BooleanField(default=False, help_text='Show the SNMP check action on device pages.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='snmp_community',
            field=models.CharField(default='public', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='snmp_port',
            field=models.PositiveIntegerField(default=161),
        ),
        migrations.CreateModel(
            name='BandwidthSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_sent', models.BigIntegerField()),
                ('bytes_recv', models.BigIntegerField()),
                ('sent_bps', models.FloatField(blank=True, null=True)),
                ('recv_bps', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
