# Generated by Django 5.2.14 on 2026-08-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_bandwidth_and_snmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='scan_subnet',
            field=models.CharField(default='10.116.145.0/24', max_length=50),
        ),
    ]
