# Generated by Django 5.2.14 on 2026-08-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_alter_systemsettings_scan_subnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='scan_subnet',
            field=models.CharField(default='192.168.1.1/24', max_length=50),
        ),
    ]
